logging.level.root=${LOG_LEVEL:WARN}
#logging.file.name=${LOG_FILE_NAME:/path-to-log-file.log}
spring.jpa.show-sql=${JPA_SHOW_URL:false}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:false}

#Just simulating some config for qa responsibility
contact.phone=+91-1234567891
contact.email=qa@eazystore.com
contact.address=123 Main Street, London, UK